// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.


 */
const sectionHeader = (title) => ({
  type: "html",
  value: title,
  className: "navbar__category",
});


const docSidebar = {
  // module.exports = {
  docSidebar: [
    sectionHeader("GETTING STARTED"),
    'intro',
    // 'community/contributing',
    // 'getting-started',



    // GETTING STARTED


    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description:
          "Let's learn about get started with OLake!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },

    // INSTALL 

    {
      type: 'category',
      label: 'Install',
      link: {
        type: 'generated-index',
        title: 'Install OLake',
        description:
          "Let's learn about how to install OLake!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'install', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },


    // CONNECTORS
    sectionHeader("CONNECTORS"),
    {
      type: 'category',
      label: 'Sources',
      link: {
        type: 'generated-index',
        title: 'OLake Connectors',
        description:
          "Let's learn about the most important OLake Connectors!",
      },
      items: [
        'connectors/overview',
        {
          type: 'category',
          label: 'MongoDB',
          link: {
            type: 'generated-index',
            title: 'OLake MongoDB Connectors',
            description:
              "Let's learn about MongoDB OLake Connectors!",
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'connectors/mongodb', // Generate sidebar slice from docs/tutorials/easy
            },
          ],
        },

        {
          type: 'category',
          label: 'Postgres',
          link: {
            type: 'generated-index',
            title: 'OLake Postgres Connectors',
            description:
              "Let's learn about Postgres OLake Connectors!",
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'connectors/postgres', // Generate sidebar slice from docs/tutorials/easy
            },
          ],
        },

        {
          type: 'category',
          label: 'MySQL',
          link: {
            type: 'generated-index',
            title: 'OLake MySQL Connectors',
            description:
              "Let's learn about MySQL OLake Connectors!",
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'connectors/mysql', // Generate sidebar slice from docs/tutorials/easy
            },
          ],
        },
      ],
    },



    // Writers


    {
      type: 'category',
      label: 'Destinations (Writers)',
      link: {
        type: 'generated-index',
        title: 'Writers',
        description:
          "Let's learn about writers for OLake!",
      },
      items: [
        'writers/overview',
        {
          type: 'category',
          label: 'AWS S3',
          link: {
            type: 'generated-index',
            title: 'OLake S3 Writer',
            description:
              "Let's learn about OLake S3 Writer!",
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'writers/s3', 
            },
          ],
        },
        {
          type: 'category',
          label: 'Apache Iceberg',
          link: {
            type: 'generated-index',
            title: 'OLake Apache Iceberg Writer',
            description:
              "Let's learn about OLake Apache Iceberg Writer!",
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'writers/iceberg', 
            },
          ],
        },
        'writers/local'
      ],
    },




    // OLake Features

    {
      type: 'category',
      label: 'Features',
      link: {
        type: 'generated-index',
        title: 'Features',
        description:
          "Let's learn about OLake Features!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'features', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },


    // Core

    {
      type: 'category',
      label: 'Understanding OLake',
      link: {
        type: 'generated-index',
        title: 'Understanding OLake',
        description:
          "Let's learn about Core architecture for OLake!",
      },
      items: [
        {
          type: 'category',
          label: 'Configurations',
          link: {
            type: 'generated-index',
            title: 'Configurations',
            description:
              "Let's learn about Core architecture for OLake!",
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'core/configs', // Generate sidebar slice from docs/tutorials/easy
            },
          ],
        },
        'core/architecture',
        'core/cli',
        'core/state-controller'
      ],
    },




    // Tutorials

    // {
    //   type: 'category',
    //   label: 'Tutorials',
    //   link: {
    //     type: 'generated-index',
    //     title: 'Tutorials',
    //     description:
    //       "Let's learn about OLake Tutorials",
    //   },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'tutorials', // Generate sidebar slice from docs/tutorials/easy
    //     },
    //   ],
    // },



    // Community
    sectionHeader("COMMUNITY"),

    {
      type: 'category',
      
      label: 'Contributing',
      link: {
        type: 'generated-index',
        title: 'Contributing',
        description:
          "OLake Community related docs!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'community', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },


    // Resources

    {
      type: 'category',
      label: 'Resources',
      link: {
        type: 'generated-index',
        title: 'Resources',
        description:
          "OLake Resources related docs!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'resources', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },

    'roadmap',
    'faqs',
    'release-notes',
  ],
};

export default docSidebar;