// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.


 */
const sectionHeader = (title) => ({
  type: "html",
  value: title,
  className: "navbar__category",
});


const docSidebar = {
  // module.exports = {
  docSidebar: [
    sectionHeader("GETTING STARTED"),
    'intro',

    // GETTING STARTED

    {
      type: 'category',
      label: 'Getting Started',      
      items: [
        'getting-started/overview',
        'getting-started/olake-ui',
        'getting-started/postgres',
        'getting-started/mysql',
        'getting-started/mongodb',
        'getting-started/oracle',
      ],
    },

    {
      type: 'category',
      label: 'Playground',
      items: [
        {
          type: 'autogenerated',
          dirName: 'playground',
        },
      ],
    },

    // INSTALL 

    {
      type: 'category',
      label: 'Install',
      items: [
        {
          type: 'autogenerated',
          dirName: 'install', 
        },
      ],
    },

    sectionHeader("USE OLAKE"),


    {
      type: 'category',
      label: 'Jobs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'jobs',
        },
      ],
    },


    {
      type: 'category',
      label: 'Features',
      items: [
        {
          type: 'autogenerated',
          dirName: 'features', 
        },
      ],
    },

    {
      type: 'category',
      label: 'Understanding OLake',
      items: [
        {
          type: 'category',
          label: 'Configurations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'core/configs', 
            },
          ],
        },
        'core/architecture',
        'core/cli',
        'core/state-controller',
        'core/use-cases',
      ],
    },


    // CONNECTORS
    sectionHeader("CONNECTORS"),
    {
      type: 'category',
      label: 'Sources',
      items: [
        'connectors/overview',
        {
          type: 'category',
          label: 'Postgres',
          items: [
            'connectors/postgres/overview',
            'connectors/postgres/config',
            'connectors/postgres/benchmarks',
            {
              type: 'category',
              label: 'Setup',
              items: [
                'connectors/postgres/setup/local',
              ],
            },
            'connectors/postgres/troubleshooting',
          ],
        },

        {
          type: 'category',
          label: 'MongoDB',
          items: [
            'connectors/mongodb/overview',
            'connectors/mongodb/config',
            'connectors/mongodb/benchmarks',
            {
              type: 'category',
              label: 'Setup',
              items: [
                'connectors/mongodb/setup/local',
              ],
            },
            'connectors/mongodb/troubleshooting',
          ],
        },

        {
          type: 'category',
          label: 'MySQL',
          items: [
            'connectors/mysql/overview',
            'connectors/mysql/config',
            'connectors/mysql/benchmarks',
            {
              type: 'category',
              label: 'Setup',
              items: [
                'connectors/mysql/setup/local',
              ],
            },
            'connectors/mysql/troubleshooting',
          ],
        },

        {
          type: 'category',
          label: 'Oracle',
          items: [
            'connectors/oracle/overview',
            'connectors/oracle/config',
            'connectors/oracle/troubleshooting',
          ],
        },
      ],
    },


    // Writers
    {
      type: 'category',
      label: 'Destinations',
      items: [
        'writers/overview',
        {
          type: 'category',
          label: 'Apache Iceberg',
          items: [
            'writers/iceberg/overview',
            {
              type: 'category',
              label: 'Catalogs',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'writers/iceberg/catalog', 
                },
              ],
            },
            'writers/iceberg/azure',
            'writers/iceberg/gcs',
            'writers/iceberg/s3-tables',
            'writers/iceberg/unity-catalog',
            'writers/iceberg/partitioning',
            'writers/iceberg/docker-compose',
            'writers/iceberg/troubleshooting',
          ],
        },

        {
          type: 'category',
          label: 'Parquet Writer',
          items: [
            'writers/parquet/s3',
            'writers/parquet/config',
            'writers/parquet/partitioning',
            'writers/parquet/permission',
            'writers/parquet/gcs',
            'writers/parquet/local',
            
          ],
        },

      ],
    },

    // Community
    sectionHeader("COMMUNITY"),

    {
      type: 'category',

      label: 'Contributing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'community', 
        },
      ],
    },


    // Resources

    {
      type: 'category',
      label: 'Resources',
      items: [
        {
          type: 'autogenerated',
          dirName: 'resources', 
        },
      ],
    },

    'roadmap',
    'faqs',
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'release', 
        },
      ],
    },
  ],
};

export default docSidebar;