module.exports = {
  docs: [
    'intro',
    'community/contributing',
    'getting-started',
    {
      type: 'category',
      label: 'Connectors',
      link: {
        type: 'generated-index',
        title: 'OLake Connectors',
        description:
          "Let's learn about the most important OLake Connectors!",
      },
      items: [
        {
          type: 'category',
          label: 'MongoDB',
          link: {
            type: 'generated-index',
            title: 'OLake MongoDB Connectors',
            description:
              "Let's learn about MongoDB OLake Connectors!",
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'connectors/mongodb', // Generate sidebar slice from docs/tutorials/easy
            },
          ],
        },
        {
          type: 'category',
          label: 'Postgres',
          link: {
            type: 'generated-index',
            title: 'OLake Postgres Connectors',
            description:
              "Let's learn about Postgres OLake Connectors!",
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'connectors/postgres', // Generate sidebar slice from docs/tutorials/easy
            },
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Install',
      link: {
        type: 'generated-index',
        title: 'Install OLake',
        description:
          "Let's learn about how to install OLake!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'install', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },

    {
      type: 'category',
      label: 'OLake Features',
      link: {
        type: 'generated-index',
        title: 'OLake Features',
        description:
          "Let's learn about OLake Features!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'features', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },

    {
      type: 'category',
      label: 'Core',
      link: {
        type: 'generated-index',
        title: 'Core',
        description:
          "Let's learn about Core architecture for OLake!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'core', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },

    {
      type: 'category',
      label: 'Writers',
      link: {
        type: 'generated-index',
        title: 'Writers',
        description:
          "Let's learn about writers for OLake!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'writers', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },

    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        title: 'Tutorials',
        description:
          "Let's learn about OLake Tutorials",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },


    {
      type: 'category',
      label: 'Community',
      link: {
        type: 'generated-index',
        title: 'Community',
        description:
          "OLake Community related docs!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'community', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },

    {
      type: 'category',
      label: 'Resources',
      link: {
        type: 'generated-index',
        title: 'Resources',
        description:
          "OLake Resources related docs!",
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'resources', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },

    'roadmap',
    'faqs',
    'release-notes',
    'troubleshooting'
  ],
};